"""
OpenSSL library patterns and symbol categorization.
"""

from typing import Dict, List

OPENSSL_LIBRARY_PATTERNS: List[str] = [
    "libcrypto",
    "libssl",
    "libcrypto_openssl",
    "libssl_openssl",
    "libopenssl",
    "libboringssl",
    "libboringcrypto",
]

DLOPEN_FUNCTION_NAMES = frozenset({'dlopen', '__libc_dlopen_mode'})
DLSYM_FUNCTION_NAMES = frozenset({'dlsym', '__libc_dlsym'})

SYMBOL_CATEGORIES: Dict[str, List[str]] = {
    "ssl_core": ["SSL_"],
    "ssl_tls": ["TLS_", "DTLS_", "TLSv1_", "DTLSv1_"],
    "crypto_evp": ["EVP_"],
    "crypto_rsa": ["RSA_", "RSAPrivateKey_", "RSAPublicKey_"],
    "crypto_dsa": ["DSA_", "DSAparams_"],
    "crypto_dh": ["DH_", "DHparams_"],
    "crypto_ec": ["EC_", "ECDSA_", "ECDH_", "ED25519_", "ED448_", "X25519_", "X448_",
                  "ECParameters_", "ECPKParameters_", "ECPARAMETERS_", "ECPKPARAMETERS_"],
    "crypto_aes": ["AES_"],
    "crypto_des": ["DES_"],
    "crypto_chacha": ["CHACHA_", "POLY1305_"],
    "crypto_hash": ["SHA1_", "SHA224_", "SHA256_", "SHA384_", "SHA512_", "SHA3_",
                   "MD4_", "MD5_", "RIPEMD160_", "BLAKE2_", "WHIRLPOOL_", "MDC2_",
                   "SHA1", "SHA224", "SHA256", "SHA384", "SHA512",
                   "MD4", "MD5", "MDC2", "RIPEMD160", "WHIRLPOOL"],
    "crypto_hmac": ["HMAC_", "CMAC_", "GMAC_", "SIPHASH_", "HMAC"],
    "crypto_bn": ["BN_"],
    "crypto_bio": ["BIO_"],
    "crypto_pem": ["PEM_"],
    "crypto_asn1": ["ASN1_", "d2i_", "i2d_",
                   "a2i_", "a2d_", "b2i_", "i2a_", "i2b_", "i2o_",
                   "i2s_", "i2t_", "i2v_", "o2i_", "s2i_", "v2i_", "asn1_",
                   "INT32_", "INT64_", "UINT32_", "UINT64_", "LONG_",
                   "BIGNUM_", "CBIGNUM_",
                   "ZINT32_", "ZINT64_", "ZLONG_", "ZUINT32_", "ZUINT64_"],
    "crypto_x509": ["X509_", "X509V3_", "X509v3_", "X509at_"],
    "crypto_x509_ext": ["GENERAL_", "PROFESSION_", "ADMISSIONS_", "ADMISSION_",
                        "NAMING_", "SXNET_", "SXNETID_", "DIST_", "POLICY_",
                        "AUTHORITY_", "PROXY_", "NAME_", "OTHERNAME_", "ACCESS_",
                        "BASIC_", "ISSUER_", "ISSUING_", "EXTENDED_", "NOTICEREF_",
                        "POLICYINFO_", "POLICYQUALINFO_", "USERNOTICE_",
                        "CERTIFICATEPOLICIES_", "EDIPARTYNAME_", "DIRECTORYSTRING_",
                        "DISPLAYTEXT_", "CRL_", "PKEY_",
                        "ASIdOrRange_", "ASIdentifierChoice_", "ASIdentifiers_",
                        "ASRange_", "IPAddressChoice_", "IPAddressFamily_",
                        "IPAddressOrRange_", "IPAddressRange_"],
    "crypto_pkcs": ["PKCS7_", "PKCS12_", "PKCS5_", "PKCS8_", "PKCS1_",
                   "PBE2PARAM_", "PBEPARAM_", "PBKDF2PARAM_",
                   "PBMAC1PARAM_", "PBMAC1_"],
    "crypto_cms": ["CMS_"],
    "crypto_ocsp": ["OCSP_"],
    "crypto_ts": ["TS_"],
    "crypto_ct": ["CT_", "SCT_", "CTLOG_"],
    "crypto_rand": ["RAND_"],
    "crypto_err": ["ERR_", "err_"],
    "crypto_obj": ["OBJ_"],
    "crypto_engine": ["ENGINE_"],
    "crypto_provider": ["OSSL_PROVIDER_", "OSSL_PARAM_", "OSSL_STORE_"],
    "crypto_kdf": ["HKDF_", "PBKDF2_", "SCRYPT_", "KDF_"],
    "crypto_sm": ["SM2_", "SM3_", "SM4_"],
    "crypto_conf": ["CONF_", "NCONF_", "conf_"],
    "crypto_ui": ["UI_"],
    "crypto_srp": ["SRP_"],
    "crypto_async": ["ASYNC_"],
    "crypto_comp": ["COMP_"],
    "crypto_smime": ["SMIME_", "ESS_"],
    "crypto_legacy": ["Camellia_", "BF_", "IDEA_", "CAST_", "RC2_", "SEED_",
                      "RC4_", "RC4"],
    "crypto_netscape": ["NETSCAPE_"],
    "crypto_dso": ["DSO_"],
    "openssl_util": ["OPENSSL_", "OSSL_", "CRYPTO_",
                    "OpenSSL_", "BUF_", "TXT_", "UTF8_"],
}

DEFAULT_SEARCH_PATHS: List[str] = [
    # OpenHarmony system paths
    "/system/lib64",
    "/system/lib",
    "/system/lib64/ndk",
    "/system/lib64/chipset-pub-sdk",
    "/system/lib64/module",
    "/system/lib64/module/security",

    # Vendor paths
    "/vendor/lib64",
    "/vendor/lib",

    # Chip SDK paths
    "/chipset/lib64",
    "/chipset/lib",

    # Standard Linux paths (for host analysis)
    "/lib64",
    "/lib",
    "/usr/lib64",
    "/usr/lib",
    "/usr/local/lib64",
    "/usr/local/lib",

    # Debian/Ubuntu multiarch paths
    "/lib/x86_64-linux-gnu",
    "/lib/aarch64-linux-gnu",
    "/lib/arm-linux-gnueabihf",
    "/usr/lib/x86_64-linux-gnu",
    "/usr/lib/aarch64-linux-gnu",
    "/usr/lib/arm-linux-gnueabihf",
]

CATEGORY_DISPLAY_ORDER: List[str] = [
    "ssl_core",
    "ssl_tls",
    "crypto_evp",
    "crypto_rsa",
    "crypto_dsa",
    "crypto_dh",
    "crypto_ec",
    "crypto_aes",
    "crypto_des",
    "crypto_chacha",
    "crypto_hash",
    "crypto_hmac",
    "crypto_bn",
    "crypto_bio",
    "crypto_pem",
    "crypto_asn1",
    "crypto_x509",
    "crypto_x509_ext",
    "crypto_pkcs",
    "crypto_cms",
    "crypto_ocsp",
    "crypto_ts",
    "crypto_ct",
    "crypto_rand",
    "crypto_err",
    "crypto_obj",
    "crypto_engine",
    "crypto_provider",
    "crypto_kdf",
    "crypto_sm",
    "crypto_conf",
    "crypto_ui",
    "crypto_srp",
    "crypto_async",
    "crypto_comp",
    "crypto_smime",
    "crypto_legacy",
    "crypto_netscape",
    "crypto_dso",
    "openssl_util",
]
